#!/usr/bin/env bash
#
# Creates the Developer ID Application certificate a signed release needs.
#
#   ./scripts/signing-setup.sh --check     # what is missing, and what to do
#   ./scripts/signing-setup.sh --dry-run   # the plan, without touching anything
#   ./scripts/signing-setup.sh             # create the certificate through asc
#   ./scripts/signing-setup.sh --csr       # ...or prepare one for the web portal
#   ./scripts/signing-setup.sh --csr --reveal   # ...and show it in Finder
#   ./scripts/signing-setup.sh --import F  # install the certificate you download
#
# ## What this is for
#
# A `--dmg` release needs two things this repository cannot create for itself:
# a **Developer ID Application** certificate, and credentials to notarize with.
# Both come from the Apple developer account.
#
# One App Store Connect API key covers both. It creates the certificate here,
# and `package-app.sh` notarizes with the same key — so there is no second
# credential, no app-specific password, and nothing that only exists in one
# machine's keychain. See scripts/signing.env.example.
#
# ## What it deliberately does not do
#
# Write anything into the repository. The private key and the certificate go to
# `~/.vbx-signing` by default, outside the checkout, because this repository is
# public and ADR-009 is that no signing material is in it. Nothing here prints a
# certificate name, a Team ID or a key id either.
#
# ## The role requirement, and why --csr exists
#
# Apple restricts Developer ID certificate creation to the **Account Holder**.
# The API refuses anything else outright:
#
#   This request is forbidden for security reasons:
#   This operation can only be performed by the Account Holder.
#
# A *Team* API key cannot hold that role — the roles offered when generating one
# do not include Account Holder — so for most accounts the API route cannot
# work at all, however the key is configured. An *Individual* key generated by
# the Account Holder carries that person's role and may; it is worth one try.
#
# When it does not, `--csr` is the route that always works: the certificate is
# requested in the web portal, signed in as the Account Holder, and `--import`
# installs what comes back. The private key is generated here either way and
# never leaves the machine.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${VBX_SIGNING_DIR:-$HOME/.vbx-signing}"
CERT_TYPE=DEVELOPER_ID_APPLICATION

CHECK=0
DRY_RUN=0
CSR_ONLY=0
REVEAL=0
IMPORT_PATH=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    --csr) CSR_ONLY=1; shift ;;
    --reveal) REVEAL=1; shift ;;
    --import) IMPORT_PATH="${2-}"; shift 2 ;;
    -h|--help) sed -n '2,48p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

say() { echo "$@"; }
fail() { echo "error: $*" >&2; exit 1; }

KEY_PATH="$OUT_DIR/developer-id.key"
CSR_PATH="$OUT_DIR/developer-id.csr"
CER_PATH="$OUT_DIR/developer-id.cer"

# Somewhere a file picker will actually show it.
#
# The request has to be uploaded through a web form, and `$OUT_DIR` is a
# dot-directory — macOS open dialogs hide those, so the file is effectively
# unreachable without knowing that ⌘⇧G exists. The key must stay private and
# out of the way; the request must not. They are different files with different
# needs, and putting both in the hidden directory served only one of them.
#
# A copy rather than a move: `$OUT_DIR` stays the canonical pair, so `--import`
# has one place to look and deleting the visible copy breaks nothing.
#
# Skipped where there is no Desktop — a CI runner, a container — rather than
# inventing a location.
VISIBLE_CSR=""
if [[ -d "$HOME/Desktop" ]]; then
  VISIBLE_CSR="$HOME/Desktop/vbx-developer-id.csr"
fi

# import_identity installs a certificate and its key, then proves the pair is
# usable for signing.
#
# Both halves matter: a certificate without its private key imports perfectly
# happily and is not an identity, which `security find-identity` will not list
# and `codesign` cannot use. That is the failure worth catching here rather than
# at the end of a release.
import_identity() {
  local cer="$1"
  [[ -f "$cer" ]] || fail "no certificate at $cer"
  [[ -f "$KEY_PATH" ]] || fail "no private key at $KEY_PATH — the CSR that produced this certificate was made elsewhere, and without its key the certificate cannot sign"

  say "==> Importing into the login keychain"
  # -T grants codesign access, so signing does not prompt for the keychain on
  # every build.
  security import "$KEY_PATH" -k login.keychain-db -T /usr/bin/codesign >/dev/null 2>&1 || true
  security import "$cer" -k login.keychain-db -T /usr/bin/codesign >/dev/null

  if ! have_developer_id; then
    fail "the certificate imported but no Developer ID identity appeared — the key and the certificate may not be a pair"
  fi

  say ""
  say "Done. Put the full identity string in scripts/signing.env:"
  say "  security find-identity -v -p codesigning | grep 'Developer ID Application'"
  say ""
  say "Then:"
  say "  ./scripts/package-app.sh --check"
}

have_developer_id() {
  security find-identity -v -p codesigning 2>/dev/null \
    | grep -q "Developer ID Application"
}

asc_authenticated() {
  command -v asc >/dev/null 2>&1 || return 1
  # `credentials` is empty when nothing is stored; the env form sets
  # environmentCredentialsComplete instead.
  asc auth status 2>/dev/null \
    | grep -qE '"credentials":\[[^]]' || \
  asc auth status 2>/dev/null \
    | grep -q '"environmentCredentialsComplete":true'
}

# ---------------------------------------------------------------------------
# --check
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# --import: install a certificate downloaded from the portal
# ---------------------------------------------------------------------------

if [[ -n "$IMPORT_PATH" ]]; then
  import_identity "$IMPORT_PATH"
  exit 0
fi

if [[ $CHECK -eq 1 ]]; then
  say "==> Signing prerequisites"

  if have_developer_id; then
    say "  Developer ID Application certificate   present"
  else
    say "  Developer ID Application certificate   MISSING"
  fi

  if command -v asc >/dev/null 2>&1; then
    if asc_authenticated; then
      say "  asc                                    authenticated"
    else
      say "  asc                                    installed, no credentials"
    fi
  else
    say "  asc                                    not installed (brew install asc)"
  fi

  say ""
  if have_developer_id; then
    say "The certificate exists. Point VBX_DEVELOPER_ID_APP at its full name:"
    say "  security find-identity -v -p codesigning | grep 'Developer ID Application'"
  else
    say "Only the **Account Holder** can create a Developer ID certificate."
    say "A Team API key cannot hold that role, so \`asc\` will refuse with:"
    say "  This operation can only be performed by the Account Holder."
    say ""
    say "The route that always works, signed in as the Account Holder:"
    say "  1. ./scripts/signing-setup.sh --csr"
    say "  2. developer.apple.com -> Certificates, Identifiers & Profiles"
    say "     -> Certificates -> + -> Developer ID Application -> upload the CSR"
    say "  3. ./scripts/signing-setup.sh --import ~/Downloads/developerID_application.cer"
    say ""
    say "Worth one try first, if you are the Account Holder: an *Individual*"
    say "API key carries your own role, unlike a Team key. Generate one, then"
    say "\`asc auth login\` and re-run this script with no arguments."
    say ""
    say "Notarization is separate and needs no special role: set"
    say "VBX_NOTARY_KEY, VBX_NOTARY_KEY_ID and VBX_NOTARY_ISSUER in"
    say "scripts/signing.env — any Team key will do, and no app-specific"
    say "password is needed."
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# --csr: prepare a request for the web portal
# ---------------------------------------------------------------------------

if [[ $CSR_ONLY -eq 1 ]]; then
  mkdir -p "$OUT_DIR"
  chmod 700 "$OUT_DIR"

  if [[ -f "$KEY_PATH" && -f "$CSR_PATH" ]]; then
    # A failed `asc` run leaves both behind: it generates the pair locally
    # before calling Apple. Reusing them is not just convenience — a second key
    # would not match a certificate issued for the first.
    say "==> Reusing the existing key and request in $OUT_DIR"
  else
    say "==> Generating a private key and certificate request"
    openssl req -new -newkey rsa:2048 -nodes \
      -keyout "$KEY_PATH" -out "$CSR_PATH" \
      -subj "/CN=Developer ID Application/O=vbx" >/dev/null 2>&1 \
      || fail "openssl could not generate the request"
    chmod 600 "$KEY_PATH"
  fi

  # The request is a public document — a public key and a subject. Copying it
  # somewhere visible discloses nothing; the private key is what stays put.
  if [[ -n "$VISIBLE_CSR" ]]; then
    cp "$CSR_PATH" "$VISIBLE_CSR"
  fi

  say ""
  say "Upload this file:"
  if [[ -n "$VISIBLE_CSR" ]]; then
    say "  $VISIBLE_CSR"
    say "  (a copy, put where a file picker can see it — delete it afterwards)"
  else
    say "  $CSR_PATH"
    say "  (in an open dialog press Cmd-Shift-G and paste that path — the"
    say "   directory is hidden and will not be listed)"
  fi
  say ""
  say "  developer.apple.com/account/resources/certificates/list"
  say "  -> + -> Software -> Developer ID Application -> upload the request"
  say "  -> Continue -> Download"
  say ""
  say "Sign in as the **Account Holder**; no other role can create one."
  say ""
  say "Then install it:"
  say "  ./scripts/signing-setup.sh --import ~/Downloads/developerID_application.cer"
  say ""
  say "The private key stays in $OUT_DIR and is never uploaded. Keep it: the"
  say "certificate cannot sign without the key whose request produced it."

  if [[ $REVEAL -eq 1 ]]; then
    open -R "${VISIBLE_CSR:-$CSR_PATH}" 2>/dev/null \
      || say "(could not reveal it in Finder)"
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# Create through asc
# ---------------------------------------------------------------------------

if have_developer_id; then
  say "A Developer ID Application certificate is already in the keychain."
  say "Nothing to do. Re-creating one would leave two valid certificates and an"
  say "ambiguous VBX_DEVELOPER_ID_APP; revoke the old one deliberately instead:"
  say "  asc certificates list --certificate-type $CERT_TYPE"
  say "  asc certificates revoke --id CERT_ID --confirm"
  exit 0
fi

say "==> Creating a $CERT_TYPE certificate"
say "  key and certificate -> $OUT_DIR (outside the repository, deliberately)"

# The credential checks come after this, so the plan can be read before anyone
# has a key — which is when it is most useful.
if [[ $DRY_RUN -eq 1 ]]; then
  say ""
  say "Would run:"
  say "  mkdir -p $OUT_DIR && chmod 700 $OUT_DIR"
  say "  asc certificates create --certificate-type $CERT_TYPE \\"
  say "    --generate-csr --key-out $KEY_PATH --csr-out $CSR_PATH"
  say "  security import $KEY_PATH -k login.keychain-db -T /usr/bin/codesign"
  say "  security import $CER_PATH -k login.keychain-db -T /usr/bin/codesign"
  if [[ -n "$VISIBLE_CSR" ]]; then
    say ""
    say "  (--csr would also copy the request to $VISIBLE_CSR,"
    say "   because a file picker cannot see into $OUT_DIR)"
  fi
  say ""
  say "Then print the identity to configure, and nothing else."
  exit 0
fi

command -v asc >/dev/null 2>&1 || fail "asc is not installed (brew install asc)"
asc_authenticated || fail "asc has no credentials — run ./scripts/signing-setup.sh --check"

mkdir -p "$OUT_DIR"
chmod 700 "$OUT_DIR"

# The private key never leaves this machine: `asc` generates it locally and
# sends only the CSR. Apple never sees it, and neither does the repository.
RESPONSE_PATH="$OUT_DIR/create-response.json"
if ! asc certificates create --certificate-type "$CERT_TYPE" \
  --generate-csr --key-out "$KEY_PATH" --csr-out "$CSR_PATH" --output json \
  > "$RESPONSE_PATH"; then
  # An empty response file left behind reads as a half-finished run.
  rm -f "$RESPONSE_PATH"
  say ""
  say "Apple refused. If it said \"only be performed by the Account Holder\","
  say "that is the expected answer for a Team key and no configuration fixes"
  say "it. Use the portal instead — the key and request just generated are"
  say "reused, so nothing is wasted:"
  say ""
  say "  ./scripts/signing-setup.sh --csr"
  exit 1
fi
chmod 600 "$KEY_PATH" "$RESPONSE_PATH"

# `certificateContent` is base64 DER. Extracted with python rather than a grep,
# because a JSON field is not a line — and read from a file rather than stdin,
# because stdin is already carrying this script.
python3 - "$CER_PATH" "$RESPONSE_PATH" <<'PY' || fail "could not read the certificate from asc's response"
import base64, json, sys
path, response = sys.argv[1], sys.argv[2]
payload = json.load(open(response))
def find(node):
    if isinstance(node, dict):
        if "certificateContent" in node:
            return node["certificateContent"]
        for value in node.values():
            found = find(value)
            if found:
                return found
    elif isinstance(node, list):
        for value in node:
            found = find(value)
            if found:
                return found
    return None
content = find(payload)
if not content:
    raise SystemExit(1)
open(path, "wb").write(base64.b64decode(content))
PY

# The response carries the certificate and nothing secret, but it is account
# data and there is no reason to leave it lying about.
rm -f "$RESPONSE_PATH"

import_identity "$CER_PATH"
