// Code generated by scripts/vendor-correlation.py from github.com/Dicklesworthstone/beads_viewer@v0.25.2 pkg/correlation/file_lock_unix.go. DO NOT EDIT.

//go:build !windows

package correlation

import (
	"os"

	"golang.org/x/sys/unix"
)

func lockFile(f *os.File) error {
	return unix.Flock(int(f.Fd()), unix.LOCK_EX)
}

func unlockFile(f *os.File) error {
	return unix.Flock(int(f.Fd()), unix.LOCK_UN)
}
