// Code generated by scripts/vendor-correlation.py from github.com/Dicklesworthstone/beads_viewer@v0.25.2 pkg/correlation/file_lock_windows.go. DO NOT EDIT.

//go:build windows

package correlation

import (
	"os"

	"golang.org/x/sys/windows"
)

func lockFile(f *os.File) error {
	handle := windows.Handle(f.Fd())
	var ol windows.Overlapped
	return windows.LockFileEx(handle, windows.LOCKFILE_EXCLUSIVE_LOCK, 0, 1, 0, &ol)
}

func unlockFile(f *os.File) error {
	handle := windows.Handle(f.Fd())
	var ol windows.Overlapped
	return windows.UnlockFileEx(handle, 0, 1, 0, &ol)
}
